FROM node:10-slim

USER node
ENV NODE_ENV=production
ENV DROPBOX_TOKEN=XXXX
ENV DROPBOX_FILEPATH=/todo.txt/done.txt
ENV PORT=3000
ENV STATIC_PATH=./static
WORKDIR /data
ADD index.js package.json package-lock.json ./
ADD static ./static
ADD views ./views
ADD node_modules ./node_modules
EXPOSE 3000
CMD npm start
